# Generated by Django 5.2.16 on 2026-07-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAssistantExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.CharField(max_length=32)),
                ('export_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_export_jobs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAssistantExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='generated', max_length=32)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.fileasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plan_assistant.planassistantexportjob')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAssistantReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.CharField(max_length=32)),
                ('person_name', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('plan', '计划'), ('summary', '总结')], max_length=32)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_review_reports', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAssistantReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('row_index', models.PositiveIntegerField(blank=True, null=True)),
                ('field', models.CharField(blank=True, max_length=120)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='plan_assistant.planassistantreviewreport')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAssistantUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.CharField(max_length=32)),
                ('upload_type', models.CharField(max_length=32)),
                ('person_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.fileasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_upload_batches', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAssistantArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.CharField(max_length=32)),
                ('is_archived', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('operated_at', models.DateTimeField(auto_now_add=True)),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_archives', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'date_batch')},
            },
        ),
        migrations.CreateModel(
            name='PlanAssistantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_batch', models.CharField(max_length=32)),
                ('person_name', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('plan', '计划'), ('summary', '总结')], max_length=32)),
                ('module', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('task_key', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=120)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('completion_status', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='organizations.organization')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.fileasset')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'date_batch', 'person_name', 'data_type'], name='plan_assist_organiz_446144_idx')],
            },
        ),
    ]
