# Generated by Django 5.2.16 on 2026-07-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=80)),
                ('status', models.CharField(default='demo', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_demos', to='assistants.assistant')),
            ],
            options={
                'unique_together': {('assistant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('node_type', models.CharField(default='demo', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowdemo')),
            ],
        ),
    ]
